### ISSUE TITLE
Explore mongodb search possibilities

### ISSUE THREAD

**Issue by tenstad** [Informasjonsforvaltning/concept-catalog#122]
db-name: `concept-catalogue`

Relevant code:
- https://github.com/Informasjonsforvaltning/concept-catalog/blob/main/src/main/kotlin/no/fdk/concept_catalog/repository/ConceptRepository.kt#L27

Desired features:
- filtering
- search across fields

**Comment by NilsOveTen** [comment]
- [ ] kan filtrere på spesifikke felt, i.e orgnr og status
- [ ] kan filterer på flere felt samtidig
- [ ] kan søke i alle felt samtidig
- [ ] kan søke i flere spesifikke felt samtidig
- [ ] kan søke og filtrere samtidig

**Comment by tenstad** [comment]
Basert på https://github.com/Informasjonsforvaltning/concept-catalog/pull/123 og dynamisk utvalg av felter samt and/or klarer vi å få det til.
