### ISSUE TITLE
Feltvalg i søk

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/concept-catalog#144]
Det skal være mulig å redusere feltene det søkes i til:
- [x] anbefalt term
- [x] frarådet term
- [x] tillatt term
- [x] definisjon
- [x] merknader (uklart om merknader er et eget felt)

Manglende felt må først legges til i `QueryFields` i modellen til `SearchOperation`, og deretter utvide `queryCriteria` i `ConceptSearchService` til å håndtere disse.

-------------------------------------------------------
[behov](https://github.com/Informasjonsforvaltning/behov/issues/789)

**Comment by KjerstiSteien** [comment]
@NilsOveTen må det gjøres noe på backend for å kunne samle "Anbefalt term", "Frarådet term og "Tillatt term" til "Term" eller gjøres dette i frontend?
