### ISSUE TITLE
Paginering i søk

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/concept-catalog#145]
Paginering blir vanskelig siden vi bare skal vise en versjon per begrep, dette kan vi atm løse vha `onlyCurrentVersions`. Men det regnes ut etter at søket er utført. Hvis vi fortsatt skal gjøre det slik må vi implementere vår egen paginering som utføres etter den filtreringen er utført. Dvs en betraktelig større jobb enn nødvendig.

For å kunne bruke det innebygde `limit`- og `skip`-funksjonaliteten til mongodb må vi filtrere etter noe i databasemodellen. Det enkleste hadde vært om vi bare alltid bare viser høyeste versjon, det er kanskje et faktisk alternativ om vi først legger til kravet om at det bare er mulig med maks ett utkast per begrep. Eller må vi vise nyeste publiserte versjon?

Hvis vi skal bruke mongodb-funksjonaliteten og vise nyeste publiserte versjon må vi utvide databasemodellen med et flagg elns som viser hva som er gjeldende versjon. Dette kan være noe knotete å klare å opprettholde logikken rundt.

**Comment by KjerstiSteien** [comment]
Det som er ønsket er at begrep med status:godkjent og høyest versjonsnummer vises. Utkast hvis det ikke finnes godkjent begrep.  

Er vi nærmest dette da? "Det enkleste hadde vært om vi bare alltid bare viser høyeste versjon, det er kanskje et faktisk alternativ om vi først legger til kravet om at det bare er mulig med maks ett utkast per begrep. Eller må vi vise nyeste publiserte versjon?" Eller er det noe ved dette som kompliserer?

**Comment by NilsOveTen** [comment]
Det blir ikke det enkleste, men skal få til en måte å håndtere det på som ikke er alt for komplisert. Må dog se litt nærmere på det først.

**Comment by KjerstiSteien** [comment]
Okay. Er det status som gjør det vanskelig? Si fra om vi skal ta en runde til på det.

**Comment by NilsOveTen** [comment]
Det er kombinasjonen av forskjellige statuser med versjoneringen. Det vi gjør nå vil ikke fungere med paginering, nå regnes den "aktive" versjonen ut etter at søket er gjennomført. For at dette skal fungere sammen med paginering må vi gjennomføre filtreringen ila søket som gjennomføres.

Hvis vi filtrerer på høyeste versjon vil utkast få presedens over godkjente. Hvis vi filtrerer på godkjente og høyeste versjon så vil utkast ikke dukke opp i det hele tatt. Så er litt usikker på hvordan vi skal få gjennomført dette, men regner med vi skal få det til.

**Comment by KjerstiSteien** [comment]
Hvis vi hadde et filter for å inkludere eller ekskludere utkast - ville det gjøre dette enklere? 
Bare en tanke: Hvis du søkte uten å velge filteret ble kun høyeste godkjente versjon vist i trefflista, og det med filteret på vises høyeste versjon uavhengig av status. 
Hvis dette gjør det enklere, kan jeg foreslå dette som et alternativ for de andre og høre hva de tenker.
