### ISSUE TITLE
Begrep Legge til flere felt enn det som er støttet i dag i backend

### ISSUE THREAD

**Issue by jeffreiffers** [Informasjonsforvaltning/concept-catalog#154]
### Feature beskrivelse
Legg til støtte for manglende felt.
https://data.norge.no/specification/skos-ap-no-begrep

### Hvorfor trenger vi det?
Vi skal til alle tider støtte spesifikasjonen.

### Forslag/løsning [Valgfritt]
Oppdater skissene og implementer manglende felt.

### Spørsmål/avklaringer
- Spesifiser hvilken felt som mangler.

### Sjekkliste (Sjekk av etter issue er laget)

- [x] Lagt til label(s)
- [x] Lagt i utviklingsbrettet (Project)

Relatert til:
- [ ] https://github.com/Informasjonsforvaltning/catalog-frontend/issues/35

**Comment by NilsOveTen** [comment]
Hvilke felter? Alle nye felt? Absolutt alle felt vi ikke støtter? Avventer design før vi gjør noe.
