### ISSUE TITLE
Gå over til å bruke concept-status fra eu

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/concept-catalog#179]
Går bort fra eksisterende begrepsstatuser og bruker i stedet `http://publications.europa.eu/resource/authority/concept-status`

Utkast -> Draft
Høring -> Candidate
Godkjent -> Current
Publisert -> Current
Ekspublisert -> Retired

---------------------------
https://github.com/Informasjonsforvaltning/behov/issues/794

**Comment by KjerstiSteien** [comment]
Noen spm: 
* Kan ikke et begrep være utgått uten å være ekspublisert?
* Kan vi vise statusene på norsk i løsningen, selv om vi bruker euvoc? 
* Løser vi alle statusene i lista på brukerhistorien med denne saken?

**Comment by NilsOveTen** [comment]
- Ja, en kan sette ting til retired uten å publisere først. Det jeg skriver var bare ment som hva vi skulle mappe de nåværende verdiene våre til
- EU har norske oversettelser på dette
- Ja, gjør vi ikke det?

**Comment by KjerstiSteien** [comment]
Da er jeg beroliget.

**Comment by jeffreiffers** [comment]
Hvordan skal **Høring** mappes til EU status?

**Comment by KjerstiSteien** [comment]
@jeffreiffers Candidate ser riktig ut for Høring. Kan vi vise de norske navnene på som er nevnt i brukerhistorien https://github.com/Informasjonsforvaltning/behov/issues/794 ?

**Comment by jeffreiffers** [comment]
Ja. Det kan vi.
