### ISSUE TITLE
Valider lista med operasjoner som levedyktige ila lagring av ChangeRequest

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/concept-catalog#262]
Sjekk at det er mulig å kjøre [patchOriginal](https://github.com/Informasjonsforvaltning/concept-catalog/blob/main/src/main/kotlin/no/fdk/concept_catalog/service/JsonPatchUtils.kt#L13) med lista av operasjoner ila [validateJsonPatchOperations](https://github.com/Informasjonsforvaltning/concept-catalog/blob/main/src/main/kotlin/no/fdk/concept_catalog/service/ChangeRequestService.kt#L130)

**Comment by KjerstiSteien** [comment]
@terjesyl jobber du med denne, eller kan jeg unassigne deg? 
@NilsOveTen hva er denne saken knyttet til? Viktig å løse, eller noe som kan/bør vente?

**Comment by NilsOveTen** [comment]
Ja, vil si den er viktig. Hvis ikke gjør dette vil vi kunne få feil når noen prøver å godkjenne et endringsforslag. Kan jo fint bare feile da og, men er det ikke mer brukervennlig å feile litt tidligere?

**Comment by KjerstiSteien** [comment]
Oppfattet!

**Comment by terjesyl** [comment]
Bør gjøres, men jeg har ikke rukket å komme så langt enda.

**Comment by terjesyl** [comment]
Kan også tas av andre:)
