### ISSUE TITLE
Bruk høyeste versjon av begrepet i elastic

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/concept-catalog#395]
trefflista i søket skal alltid basere seg på høyeste versjon av begrepet, uansett om høyeste versjon av begrepet er publisert eller ikke

**Comment by KjerstiSteien** [comment]
Fra skatt: Jeg synes det funker veldig bra! Eneste jeg har å kommenetere på er at jeg synes "Dette begrepet har en publisert versjon" er litt langt? Foreslår å kalle det noe litt kortere og konkret som tyder på at man kan komme til den publiserte versjonen via den linken. 

Forslag til tekst på lenken: Gå til publisert versjon
