### ISSUE TITLE
[begrepsregistrering] Feiler med internal server error ved endring av "forhold til kilde"

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/concept-catalog#43]
Reprodusere:
feks ta vekk innhold i feltet "Lenke til kilde" og legg til på nytt.
 
begreps-id: https://registrering-begrep.fellesdatakatalog.digdir.no/991825827/e51d808c-f6f9-45f6-939f-b36b446760ba
{timestamp: "2021-03-29T06:57:10.244+0000", status: 500, error: "Internal Server Error",…}
error: "Internal Server Error"
message: "Invalid patch operation. Begrep id e51d808c-f6f9-45f6-939f-b36b446760ba"
path: "/begreper/e51d808c-f6f9-45f6-939f-b36b446760ba"
status: 500
timestamp: "2021-03-29T06:57:10.244+0000"

![image](https://user-images.githubusercontent.com/1702357/112798433-2b773600-906d-11eb-9063-7ef86a7602dd.png)

**Comment by jeffreiffers** [comment]
Concept-catalogue har blitt erstattet av concept-catalog i mai. Lukker saken.
