### ISSUE TITLE
Endepunkt for turtle-versjon av enkle begrep

### ISSUE THREAD

**Issue by NilsOveTen** [Informasjonsforvaltning/concept-catalog#93]

**Comment by jimjyang** [comment]
Hvis jeg forstår bakgrunnen for dette issuet rett, så har jeg et konkret eksempel her: 

URIen https://concept-catalog.fellesdatakatalog.digdir.no/collections/991825827/af1ee647-9e46-4cd8-9607-d32d1551cab3 til begrepet 'hendelse' er ikke dereferenceable og gir derfor valideringsfeil. Begrepet "bor i" https://data.norge.no/concepts/db48fa77-3f47-4d58-b4a3-41569f149c1a som gir maskinlesbar ressurs men det hjelper ikke fordi det er ovennevnte URIen som brukes av validatoren.

Dette bør rettes opp asap. Ressurser i/fra FDK skal være maskinlesbare og dermed dereferenceable.

**Comment by stigbd** [comment]
Eg har sjekka litt, og vi _har_ støtte for endepunkt på enkle begrep i dag. Men url til endepunktet er ikkje det same som uri som er oppgitt i dct:identifier. Så vi  må endre alle verdier for dct:identifier før dette fungerer. 

Ditt eksempel uri vs url:
uri: `https://concept-catalog.fellesdatakatalog.digdir.no/collections/991825827/af1ee647-9e46-4cd8-9607-d32d1551cab3`
url: `https://concept-catalog.fellesdatakatalog.digdir.no/collections/991825827/concepts/af1ee647-9e46-4cd8-9607-d32d1551cab3`

**Comment by stigbd** [comment]
Eg har sjekka litt, og vi _har_ støtte for endepunkt på enkle begrep i dag. Men url til endepunktet er ikkje det same som uri som er oppgitt i dct:identifier. Så vi  må endre alle verdier for dct:identifier før dette fungerer. 

Ditt eksempel uri vs url:
uri: `https://concept-catalog.fellesdatakatalog.digdir.no/collections/991825827/af1ee647-9e46-4cd8-9607-d32d1551cab3`
url: `https://concept-catalog.fellesdatakatalog.digdir.no/collections/991825827/concepts/af1ee647-9e46-4cd8-9607-d32d1551cab3`

**Comment by stigbd** [comment]
Eg har sjekka litt, og vi _har_ støtte for endepunkt på enkle begrep i dag. Men url til endepunktet er ikkje det same som uri som er oppgitt i dct:identifier. Så vi  må endre alle verdier for dct:identifier før dette fungerer. 

Ditt eksempel uri vs url:
uri: `https://concept-catalog.fellesdatakatalog.digdir.no/collections/991825827/af1ee647-9e46-4cd8-9607-d32d1551cab3`
url: `https://concept-catalog.fellesdatakatalog.digdir.no/collections/991825827/concepts/af1ee647-9e46-4cd8-9607-d32d1551cab3`

**Comment by stigbd** [comment]
Viss vi antar at denne tilnærminga er korrekt, kan vi få på plass ny uri i løpet av neste veke.

**Comment by NilsOveTen** [comment]
> Fikses med ETL

Ikke bare, men er veldig liten kode-endring
